### ISSUE TITLE
Homebrew integration

### ISSUE THREAD

**Issue by rngtng** [ensody/ssh-agent-inject#3] opened 2019-09-13 14:07 UTC
Nice, could you offer installation view homebew (https://brew.sh) too please? Thx!

**Comment by wkornewald** [comment] 2019-09-13 16:18
I'd love to. I've updated #1 to specifically mention brew. Marking this as duplicate of #1 if you don't mind. ;)

**Closed as completed by wkornewald** 2019-09-13 16:18 UTC
